## Data Collection using OpenWeather API

In this section, realtime weather and air quality data is collected using the OpenWeather API.The collected data will be used to create our dataset for  analysis, feature engineering, and machine learning

## import libraries for API data collection and analysis

In this step, we import the required libraries to connect with the openweather API key stored in the enviroment files.

In [2]:
# Import libraries required for API data collection

# Used to send requests to OpenWeather API
import requests

# Used to access environment variables
import os

# Used to load API keys from .env file securely
from dotenv import load_dotenv


# Load variables stored in .env file
load_dotenv()


# Retrieve OpenWeather API key
API_KEY = os.getenv("OPENWEATHER_API_KEY")


# Verify API key loading without displaying the key
if API_KEY:
    print("✅ API Key loaded successfully")
else:
    print("❌ API Key not found")

✅ API Key loaded successfully

## Get Geographic Coordinates

The OpenWeather Air Pollution API requires the latitude and longitude of a location instead of the city name.

In this step, we will convert the selected city (Nagarparkar) into geographic coordinates. These coordinates will be used in the next step to fetch real-time weather and air quality data.

In [3]:
# ==========================================================
# STEP 3 : Define Project Location
# ==========================================================

# Selected city for AQI prediction
CITY = "Nagarparkar"

# Latitude and Longitude of Nagarparkar, Sindh, Pakistan
LATITUDE = 24.357
LONGITUDE = 70.755

# Display project location
print(f" Selected City : {CITY}")
print(f" Latitude : {LATITUDE}")
print(f" Longitude : {LONGITUDE}")

 Selected City : Nagarparkar
 Latitude : 24.357
 Longitude : 70.755

## Fetch Real-time Weather and Air Quality Data

In  this step, we connect to the openweather air polution API to retrieve the current air quality data for nanagarparkar city. The API returns  data a JSON format response containing various air quality parameters, including AQI, PM2.5, PM10, CO, NO2, O3, NH3 and SO2 levels.

This raw data will be used in the next step to create a structured dataset for analysis and machine learning.

In [4]:
aqi_url = (
    f"https://api.openweathermap.org/data/2.5/air_pollution?"
    f"lat={LATITUDE}&lon={LONGITUDE}&appid={API_KEY}"
)

response = requests.get(aqi_url)

print("Status Code:", response.status_code)

aqi_data = response.json()

aqi_data

Status Code: 200

{'coord': {'lon': 70.755, 'lat': 24.357},
 'list': [{'main': {'aqi': 1},
   'components': {'co': 73.18,
    'no': 0,
    'no2': 1.48,
    'o3': 37.69,
    'so2': 1.05,
    'pm2_5': 5.44,
    'pm10': 14.43,
    'nh3': 0.41},
   'dt': 1784145156}]}

## Convert JSON response into a pandas dataframe

The data received from the OpenWeather API is in JSON format. In this step, we extract the required air quality parametars information and convert into a pandas dataframe. This structured dataframe will be used for further analysis and machine learning.

In [5]:
aqi_record={
    "city": CITY,
    "latitude": LATITUDE,
    "longitude": LONGITUDE,
    "aqi": aqi_data["list"][0]["main"]["aqi"],
    "co": aqi_data["list"][0]["components"]["co"],
    "no": aqi_data["list"][0]["components"]["no"],
    "no2": aqi_data["list"][0]["components"]["no2"],
    "o3": aqi_data["list"][0]["components"]["o3"],
    "so2": aqi_data["list"][0]["components"]["so2"],
    "pm2_5": aqi_data["list"][0]["components"]["pm2_5"],
    "pm10": aqi_data["list"][0]["components"]["pm10"],
    "nh3": aqi_data["list"][0]["components"]["nh3"]

}
import pandas as pd
aqi_df = pd.DataFrame([aqi_record])
aqi_df

,city,latitude,longitude,aqi,co,no,no2,o3,so2,pm2_5,pm10,nh3
0,Nagarparkar,24.357,70.755,1,73.18,0,1.48,37.69,1.05,5.44,14.43,0.41

## Save the Raw Dataset

After converting the API response into a Pandas DataFrame, the dataset is saved in the `data/raw` directory. Storing the raw data is an important step because it preserves the original information collected from the API. This allows us to reuse the dataset for preprocessing, exploratory data analysis (EDA), feature engineering, and machine learning without making repeated API requests.

In [6]:
aqi_df.to_csv("../data/raw/aqi_raw_data.csv", index=False)

print("Raw dataset saved successfully.")

Raw dataset saved successfully.

In [7]:
import os
print(os.getcwd())

c:\Users\chanchal_soni\Desktop\10_pearlsshine_internship\1st_project\pearls-aqi-predictor\notebooks

In [8]:
import os 
print(os.listdir())

['01_data_collection.ipynb']

In [9]:
import pandas as pd
raw_df = pd.read_csv("../data/raw/aqi_raw_data.csv")
raw_df.head()

,city,latitude,longitude,aqi,co,no,no2,o3,so2,pm2_5,pm10,nh3
0,Nagarparkar,24.357,70.755,1,73.18,0,1.48,37.69,1.05,5.44,14.43,0.41

## understand the structure of the dataset

Before performing any analysis or preprocessing, it is important to understand the structure of the dataset. This helps us identify the available features, their data types, and any potential issues such as missing values or outliers. In this step, we will load the saved raw dataset and display its first few rows to get an overview of the data.

In [10]:
raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   city       1 non-null      str
 1   latitude   1 non-null      float64
 2   longitude  1 non-null      float64
 3   aqi        1 non-null      int64
 4   co         1 non-null      float64
 5   no         1 non-null      int64
 6   no2        1 non-null      float64
 7   o3         1 non-null      float64
 8   so2        1 non-null      float64
 9   pm2_5      1 non-null      float64
 10  pm10       1 non-null      float64
 11  nh3        1 non-null      float64
dtypes: float64(9), int64(2), str(1)
memory usage: 239.0 bytes

## Basic dataset exploration

After understanding the data structure, the next step is to perform a basic exploration. This helps us quickly inspect the data, understand its dimensions, review column names, and generate summary statistics before moving to preprocessning and feature engineering.

In [11]:
# display first 5 rows of the dataset
raw_df.head()

,city,latitude,longitude,aqi,co,no,no2,o3,so2,pm2_5,pm10,nh3
0,Nagarparkar,24.357,70.755,1,73.18,0,1.48,37.69,1.05,5.44,14.43,0.41

In [12]:
# Display the last 5 rows of the dataset
raw_df.tail()

,city,latitude,longitude,aqi,co,no,no2,o3,so2,pm2_5,pm10,nh3
0,Nagarparkar,24.357,70.755,1,73.18,0,1.48,37.69,1.05,5.44,14.43,0.41

In [13]:
## check dataset dimensions
raw_df.shape

(1, 12)

In [14]:
## display column names
raw_df.columns

Index(['city', 'latitude', 'longitude', 'aqi', 'co', 'no', 'no2', 'o3', 'so2',
       'pm2_5', 'pm10', 'nh3'],
      dtype='str')

In [15]:
## generate summary statistics for numerical columns
raw_df.describe(include='all')

,city,latitude,longitude,aqi,co,no,no2,o3,so2,pm2_5,pm10,nh3
count,1,1.000,1.000,1.0,1.00,1.0,1.00,1.00,1.00,1.00,1.00,1.00
unique,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Nagarparkar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,24.357,70.755,1.0,73.18,0.0,1.48,37.69,1.05,5.44,14.43,0.41
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,24.357,70.755,1.0,73.18,0.0,1.48,37.69,1.05,5.44,14.43,0.41
25%,NaN,24.357,70.755,1.0,73.18,0.0,1.48,37.69,1.05,5.44,14.43,0.41
50%,NaN,24.357,70.755,1.0,73.18,0.0,1.48,37.69,1.05,5.44,14.43,0.41
75%,NaN,24.357,70.755,1.0,73.18,0.0,1.48,37.69,1.05,5.44,14.43,0.41
max,NaN,24.357,70.755,1.0,73.18,0.0,1.48,37.69,1.05,5.44,14.43,0.41

In [16]:
raw_df.isnull().sum().sum()

np.int64(0)

In [17]:
raw_df.shape

(1, 12)

# Check Historical AQI API Access

In this step, we will verify whether the OpenWeather API key has permission to access historical air pollution data. If access is available, we will build our training dataset directly from historical records for Nagarparkar.

In [18]:
city="Nagarparkar"
lat=24.357
lon=70.755

In [19]:
import requests
import time
from datetime import datetime, timedelta

# Last 5 days
end = int(time.time())
start = int((datetime.now() - timedelta(days=5)).timestamp())

history_url = (
f"https://api.openweathermap.org/data/2.5/air_pollution/history"
f"?lat={lat}&lon={lon}&start={start}&end={end}&appid={API_KEY}"
)

response = requests.get(history_url)

print("Status Code:", response.status_code)
print(response.json())

Status Code: 200
{'coord': {'lon': 70.755, 'lat': 24.357}, 'list': [{'main': {'aqi': 3}, 'components': {'co': 67.63, 'no': 0, 'no2': 0.68, 'o3': 38.67, 'so2': 0.74, 'pm2_5': 14.64, 'pm10': 61.21, 'nh3': 0.24}, 'dt': 1783731600}, {'main': {'aqi': 3}, 'components': {'co': 68.75, 'no': 0.01, 'no2': 0.88, 'o3': 38.99, 'so2': 0.81, 'pm2_5': 14.09, 'pm10': 58.51, 'nh3': 0.25}, 'dt': 1783735200}, {'main': {'aqi': 3}, 'components': {'co': 70.31, 'no': 0.06, 'no2': 1.07, 'o3': 40.05, 'so2': 0.9, 'pm2_5': 13.57, 'pm10': 55.94, 'nh3': 0.23}, 'dt': 1783738800}, {'main': {'aqi': 3}, 'components': {'co': 71.19, 'no': 0.12, 'no2': 1.03, 'o3': 43.18, 'so2': 0.95, 'pm2_5': 13.26, 'pm10': 55.49, 'nh3': 0.2}, 'dt': 1783742400}, {'main': {'aqi': 3}, 'components': {'co': 71.06, 'no': 0.14, 'no2': 0.8, 'o3': 47.91, 'so2': 0.95, 'pm2_5': 12.99, 'pm10': 53.78, 'nh3': 0.18}, 'dt': 1783746000}, {'main': {'aqi': 3}, 'components': {'co': 70.67, 'no': 0.13, 'no2': 0.6, 'o3': 52.72, 'so2': 0.93, 'pm2_5': 12.36, 'pm10': 50.85, 'nh3': 0.16}, 'dt': 1783749600}, {'main': {'aqi': 2}, 'components': {'co': 71.1, 'no': 0.11, 'no2': 0.5, 'o3': 56.66, 'so2': 0.88, 'pm2_5': 11.5, 'pm10': 48.63, 'nh3': 0.14}, 'dt': 1783753200}, {'main': {'aqi': 2}, 'components': {'co': 70.89, 'no': 0.1, 'no2': 0.49, 'o3': 56.53, 'so2': 0.85, 'pm2_5': 11.09, 'pm10': 47.48, 'nh3': 0.13}, 'dt': 1783756800}, {'main': {'aqi': 2}, 'components': {'co': 70.18, 'no': 0.11, 'no2': 0.51, 'o3': 53.66, 'so2': 0.85, 'pm2_5': 11.47, 'pm10': 49.35, 'nh3': 0.12}, 'dt': 1783760400}, {'main': {'aqi': 3}, 'components': {'co': 70.24, 'no': 0.11, 'no2': 0.54, 'o3': 50.72, 'so2': 0.85, 'pm2_5': 11.84, 'pm10': 51.28, 'nh3': 0.11}, 'dt': 1783764000}, {'main': {'aqi': 3}, 'components': {'co': 70.4, 'no': 0.1, 'no2': 0.66, 'o3': 47.93, 'so2': 0.86, 'pm2_5': 11.95, 'pm10': 52.08, 'nh3': 0.12}, 'dt': 1783767600}, {'main': {'aqi': 3}, 'components': {'co': 71.24, 'no': 0.08, 'no2': 0.86, 'o3': 45.6, 'so2': 0.87, 'pm2_5': 11.99, 'pm10': 52.32, 'nh3': 0.13}, 'dt': 1783771200}, {'main': {'aqi': 3}, 'components': {'co': 71.46, 'no': 0.05, 'no2': 1.05, 'o3': 42.9, 'so2': 0.89, 'pm2_5': 12.28, 'pm10': 54.06, 'nh3': 0.15}, 'dt': 1783774800}, {'main': {'aqi': 3}, 'components': {'co': 71.05, 'no': 0.01, 'no2': 1.15, 'o3': 40.03, 'so2': 0.94, 'pm2_5': 13, 'pm10': 57.57, 'nh3': 0.16}, 'dt': 1783778400}, {'main': {'aqi': 3}, 'components': {'co': 70.46, 'no': 0, 'no2': 1.09, 'o3': 38.37, 'so2': 0.98, 'pm2_5': 13.47, 'pm10': 60.38, 'nh3': 0.17}, 'dt': 1783782000}, {'main': {'aqi': 3}, 'components': {'co': 69.74, 'no': 0, 'no2': 1, 'o3': 37.86, 'so2': 1, 'pm2_5': 13.78, 'pm10': 62.36, 'nh3': 0.18}, 'dt': 1783785600}, {'main': {'aqi': 3}, 'components': {'co': 69.23, 'no': 0, 'no2': 0.99, 'o3': 37.73, 'so2': 1.05, 'pm2_5': 14.59, 'pm10': 68.11, 'nh3': 0.18}, 'dt': 1783789200}, {'main': {'aqi': 3}, 'components': {'co': 68.72, 'no': 0, 'no2': 0.98, 'o3': 37.22, 'so2': 1.09, 'pm2_5': 15.72, 'pm10': 75.49, 'nh3': 0.18}, 'dt': 1783792800}, {'main': {'aqi': 3}, 'components': {'co': 67.99, 'no': 0, 'no2': 0.92, 'o3': 36.69, 'so2': 1.06, 'pm2_5': 16.66, 'pm10': 80.66, 'nh3': 0.18}, 'dt': 1783796400}, {'main': {'aqi': 3}, 'components': {'co': 67.9, 'no': 0, 'no2': 0.84, 'o3': 36.73, 'so2': 1.02, 'pm2_5': 17.21, 'pm10': 83.01, 'nh3': 0.18}, 'dt': 1783800000}, {'main': {'aqi': 3}, 'components': {'co': 68.07, 'no': 0, 'no2': 0.77, 'o3': 37.13, 'so2': 0.98, 'pm2_5': 17.64, 'pm10': 85, 'nh3': 0.19}, 'dt': 1783803600}, {'main': {'aqi': 3}, 'components': {'co': 67.98, 'no': 0, 'no2': 0.73, 'o3': 37.35, 'so2': 0.94, 'pm2_5': 18.12, 'pm10': 85.9, 'nh3': 0.19}, 'dt': 1783807200}, {'main': {'aqi': 3}, 'components': {'co': 67.8, 'no': 0, 'no2': 0.71, 'o3': 37.24, 'so2': 0.91, 'pm2_5': 18.36, 'pm10': 85.91, 'nh3': 0.2}, 'dt': 1783810800}, {'main': {'aqi': 3}, 'components': {'co': 67.36, 'no': 0, 'no2': 0.72, 'o3': 36.98, 'so2': 0.9, 'pm2_5': 18.17, 'pm10': 84.94, 'nh3': 0.21}, 'dt': 1783814400}, {'main': {'aqi': 3}, 'components': {'co': 67.48, 'no': 0, 'no2': 0.69, 'o3': 37.01, 'so2': 0.85, 'pm2_5': 18.29, 'pm10': 86.99, 'nh3': 0.2}, 'dt': 1783818000}, {'main': {'aqi': 3}, 'components': {'co': 68.29, 'no': 0.02, 'no2': 0.87, 'o3': 36.61, 'so2': 0.91, 'pm2_5': 18.15, 'pm10': 84.37, 'nh3': 0.2}, 'dt': 1783821600}, {'main': {'aqi': 3}, 'components': {'co': 69.45, 'no': 0.11, 'no2': 0.96, 'o3': 36.77, 'so2': 1, 'pm2_5': 17.96, 'pm10': 81.9, 'nh3': 0.18}, 'dt': 1783825200}, {'main': {'aqi': 3}, 'components': {'co': 70.03, 'no': 0.19, 'no2': 0.87, 'o3': 39.01, 'so2': 1.11, 'pm2_5': 17.8, 'pm10': 81.42, 'nh3': 0.16}, 'dt': 1783828800}, {'main': {'aqi': 3}, 'components': {'co': 69.82, 'no': 0.18, 'no2': 0.73, 'o3': 42.7, 'so2': 1.16, 'pm2_5': 17.72, 'pm10': 82.15, 'nh3': 0.14}, 'dt': 1783832400}, {'main': {'aqi': 3}, 'components': {'co': 69.46, 'no': 0.16, 'no2': 0.6, 'o3': 46.16, 'so2': 1.15, 'pm2_5': 17.91, 'pm10': 83.96, 'nh3': 0.12}, 'dt': 1783836000}, {'main': {'aqi': 3}, 'components': {'co': 70.12, 'no': 0.12, 'no2': 0.53, 'o3': 49.39, 'so2': 1.06, 'pm2_5': 18.6, 'pm10': 89.99, 'nh3': 0.07}, 'dt': 1783839600}, {'main': {'aqi': 3}, 'components': {'co': 70.12, 'no': 0.11, 'no2': 0.52, 'o3': 49.89, 'so2': 0.99, 'pm2_5': 19.39, 'pm10': 96.84, 'nh3': 0.03}, 'dt': 1783843200}, {'main': {'aqi': 4}, 'components': {'co': 69.86, 'no': 0.1, 'no2': 0.56, 'o3': 48.27, 'so2': 0.98, 'pm2_5': 19.83, 'pm10': 100.7, 'nh3': 0.02}, 'dt': 1783846800}, {'main': {'aqi': 4}, 'components': {'co': 70.17, 'no': 0.09, 'no2': 0.62, 'o3': 46.26, 'so2': 0.98, 'pm2_5': 20.16, 'pm10': 102.92, 'nh3': 0.02}, 'dt': 1783850400}, {'main': {'aqi': 4}, 'components': {'co': 70.45, 'no': 0.08, 'no2': 0.74, 'o3': 43.73, 'so2': 1, 'pm2_5': 20.23, 'pm10': 102.34, 'nh3': 0.02}, 'dt': 1783854000}, {'main': {'aqi': 4}, 'components': {'co': 71.3, 'no': 0.06, 'no2': 0.91, 'o3': 41.67, 'so2': 1.03, 'pm2_5': 20.29, 'pm10': 100.82, 'nh3': 0.04}, 'dt': 1783857600}, {'main': {'aqi': 3}, 'components': {'co': 71.85, 'no': 0.03, 'no2': 1.06, 'o3': 40.26, 'so2': 1.05, 'pm2_5': 20.13, 'pm10': 98.23, 'nh3': 0.06}, 'dt': 1783861200}, {'main': {'aqi': 3}, 'components': {'co': 71.97, 'no': 0, 'no2': 1.11, 'o3': 39.25, 'so2': 1.08, 'pm2_5': 19.21, 'pm10': 91.48, 'nh3': 0.1}, 'dt': 1783864800}, {'main': {'aqi': 3}, 'components': {'co': 71.69, 'no': 0, 'no2': 1.06, 'o3': 38.53, 'so2': 1.1, 'pm2_5': 18.13, 'pm10': 84.06, 'nh3': 0.13}, 'dt': 1783868400}, {'main': {'aqi': 3}, 'components': {'co': 70.93, 'no': 0, 'no2': 1, 'o3': 37.83, 'so2': 1.12, 'pm2_5': 17.68, 'pm10': 80.55, 'nh3': 0.16}, 'dt': 1783872000}, {'main': {'aqi': 3}, 'components': {'co': 70.99, 'no': 0, 'no2': 1, 'o3': 37.49, 'so2': 1.16, 'pm2_5': 18.29, 'pm10': 82.91, 'nh3': 0.18}, 'dt': 1783875600}, {'main': {'aqi': 3}, 'components': {'co': 71.03, 'no': 0, 'no2': 0.99, 'o3': 37.34, 'so2': 1.16, 'pm2_5': 19.11, 'pm10': 86.66, 'nh3': 0.2}, 'dt': 1783879200}, {'main': {'aqi': 3}, 'components': {'co': 70.53, 'no': 0, 'no2': 0.93, 'o3': 36.99, 'so2': 1.12, 'pm2_5': 19.62, 'pm10': 89.18, 'nh3': 0.2}, 'dt': 1783882800}, {'main': {'aqi': 3}, 'components': {'co': 70, 'no': 0, 'no2': 0.86, 'o3': 36.71, 'so2': 1.09, 'pm2_5': 19.68, 'pm10': 89.72, 'nh3': 0.21}, 'dt': 1783886400}, {'main': {'aqi': 3}, 'components': {'co': 69.79, 'no': 0, 'no2': 0.8, 'o3': 36.41, 'so2': 1.06, 'pm2_5': 19.22, 'pm10': 87.88, 'nh3': 0.23}, 'dt': 1783890000}, {'main': {'aqi': 3}, 'components': {'co': 69.49, 'no': 0, 'no2': 0.75, 'o3': 36.14, 'so2': 1.02, 'pm2_5': 18.42, 'pm10': 84.46, 'nh3': 0.25}, 'dt': 1783893600}, {'main': {'aqi': 3}, 'components': {'co': 69.6, 'no': 0, 'no2': 0.73, 'o3': 36.07, 'so2': 0.99, 'pm2_5': 17.57, 'pm10': 80.8, 'nh3': 0.26}, 'dt': 1783897200}, {'main': {'aqi': 3}, 'components': {'co': 69.8, 'no': 0, 'no2': 0.77, 'o3': 36.35, 'so2': 0.99, 'pm2_5': 16.87, 'pm10': 77.91, 'nh3': 0.28}, 'dt': 1783900800}, {'main': {'aqi': 3}, 'components': {'co': 70.24, 'no': 0, 'no2': 0.89, 'o3': 36.44, 'so2': 1.02, 'pm2_5': 16.42, 'pm10': 76.05, 'nh3': 0.29}, 'dt': 1783904400}, {'main': {'aqi': 3}, 'components': {'co': 71.42, 'no': 0.02, 'no2': 1.15, 'o3': 36.21, 'so2': 1.12, 'pm2_5': 16.17, 'pm10': 75.01, 'nh3': 0.29}, 'dt': 1783908000}, {'main': {'aqi': 3}, 'components': {'co': 72.9, 'no': 0.12, 'no2': 1.33, 'o3': 36.19, 'so2': 1.24, 'pm2_5': 16.08, 'pm10': 74.79, 'nh3': 0.27}, 'dt': 1783911600}, {'main': {'aqi': 3}, 'components': {'co': 73.23, 'no': 0.22, 'no2': 1.25, 'o3': 37.61, 'so2': 1.35, 'pm2_5': 16.13, 'pm10': 75.32, 'nh3': 0.24}, 'dt': 1783915200}, {'main': {'aqi': 3}, 'components': {'co': 72.24, 'no': 0.22, 'no2': 1.09, 'o3': 39.82, 'so2': 1.41, 'pm2_5': 16.14, 'pm10': 75.92, 'nh3': 0.21}, 'dt': 1783918800}, {'main': {'aqi': 3}, 'components': {'co': 71.46, 'no': 0.18, 'no2': 0.95, 'o3': 42.4, 'so2': 1.42, 'pm2_5': 16.02, 'pm10': 76.06, 'nh3': 0.19}, 'dt': 1783922400}, {'main': {'aqi': 3}, 'components': {'co': 71.81, 'no': 0.15, 'no2': 0.81, 'o3': 46.01, 'so2': 1.33, 'pm2_5': 15.41, 'pm10': 73.64, 'nh3': 0.16}, 'dt': 1783926000}, {'main': {'aqi': 3}, 'components': {'co': 71.93, 'no': 0.14, 'no2': 0.72, 'o3': 47.85, 'so2': 1.23, 'pm2_5': 14.65, 'pm10': 70.49, 'nh3': 0.14}, 'dt': 1783929600}, {'main': {'aqi': 3}, 'components': {'co': 71.72, 'no': 0.13, 'no2': 0.69, 'o3': 47.18, 'so2': 1.16, 'pm2_5': 14.41, 'pm10': 70.1, 'nh3': 0.13}, 'dt': 1783933200}, {'main': {'aqi': 3}, 'components': {'co': 71.46, 'no': 0.13, 'no2': 0.72, 'o3': 45.17, 'so2': 1.12, 'pm2_5': 14.23, 'pm10': 70.35, 'nh3': 0.13}, 'dt': 1783936800}, {'main': {'aqi': 3}, 'components': {'co': 71.74, 'no': 0.15, 'no2': 0.77, 'o3': 43.59, 'so2': 1.1, 'pm2_5': 13.74, 'pm10': 68.22, 'nh3': 0.13}, 'dt': 1783940400}, {'main': {'aqi': 3}, 'components': {'co': 72.91, 'no': 0.16, 'no2': 0.89, 'o3': 42.82, 'so2': 1.09, 'pm2_5': 13.21, 'pm10': 64.76, 'nh3': 0.15}, 'dt': 1783944000}, {'main': {'aqi': 3}, 'components': {'co': 73.57, 'no': 0.11, 'no2': 1.12, 'o3': 41.06, 'so2': 1.09, 'pm2_5': 12.96, 'pm10': 61.38, 'nh3': 0.17}, 'dt': 1783947600}, {'main': {'aqi': 3}, 'components': {'co': 73.47, 'no': 0.02, 'no2': 1.34, 'o3': 38.4, 'so2': 1.11, 'pm2_5': 12.79, 'pm10': 56.97, 'nh3': 0.2}, 'dt': 1783951200}, {'main': {'aqi': 3}, 'components': {'co': 72.76, 'no': 0, 'no2': 1.32, 'o3': 36.65, 'so2': 1.12, 'pm2_5': 12.6, 'pm10': 52.11, 'nh3': 0.23}, 'dt': 1783954800}, {'main': {'aqi': 2}, 'components': {'co': 71.68, 'no': 0, 'no2': 1.24, 'o3': 35.69, 'so2': 1.1, 'pm2_5': 12.21, 'pm10': 47.1, 'nh3': 0.24}, 'dt': 1783958400}, {'main': {'aqi': 2}, 'components': {'co': 71.43, 'no': 0, 'no2': 1.21, 'o3': 35.46, 'so2': 1.1, 'pm2_5': 12.14, 'pm10': 44.64, 'nh3': 0.26}, 'dt': 1783962000}, {'main': {'aqi': 2}, 'components': {'co': 71.4, 'no': 0, 'no2': 1.19, 'o3': 35.59, 'so2': 1.08, 'pm2_5': 12.01, 'pm10': 43.52, 'nh3': 0.26}, 'dt': 1783965600}, {'main': {'aqi': 2}, 'components': {'co': 70.74, 'no': 0, 'no2': 1.1, 'o3': 35.59, 'so2': 1.02, 'pm2_5': 11.37, 'pm10': 41.24, 'nh3': 0.26}, 'dt': 1783969200}, {'main': {'aqi': 2}, 'components': {'co': 70.44, 'no': 0, 'no2': 0.98, 'o3': 35.78, 'so2': 0.96, 'pm2_5': 10.74, 'pm10': 39.99, 'nh3': 0.26}, 'dt': 1783972800}, {'main': {'aqi': 2}, 'components': {'co': 70.11, 'no': 0, 'no2': 0.88, 'o3': 36.03, 'so2': 0.9, 'pm2_5': 10.26, 'pm10': 39.78, 'nh3': 0.27}, 'dt': 1783976400}, {'main': {'aqi': 2}, 'components': {'co': 69.82, 'no': 0, 'no2': 0.81, 'o3': 36.21, 'so2': 0.85, 'pm2_5': 9.87, 'pm10': 39.22, 'nh3': 0.28}, 'dt': 1783980000}, {'main': {'aqi': 2}, 'components': {'co': 69.59, 'no': 0, 'no2': 0.76, 'o3': 36.45, 'so2': 0.81, 'pm2_5': 9.34, 'pm10': 36.6, 'nh3': 0.28}, 'dt': 1783983600}, {'main': {'aqi': 2}, 'components': {'co': 69.62, 'no': 0, 'no2': 0.77, 'o3': 36.5, 'so2': 0.78, 'pm2_5': 8.84, 'pm10': 33.49, 'nh3': 0.29}, 'dt': 1783987200}, {'main': {'aqi': 2}, 'components': {'co': 69.88, 'no': 0, 'no2': 0.88, 'o3': 36.34, 'so2': 0.81, 'pm2_5': 8.44, 'pm10': 30.69, 'nh3': 0.29}, 'dt': 1783990800}, {'main': {'aqi': 2}, 'components': {'co': 70.93, 'no': 0.01, 'no2': 1.16, 'o3': 36.04, 'so2': 0.9, 'pm2_5': 8.09, 'pm10': 27.81, 'nh3': 0.29}, 'dt': 1783994400}, {'main': {'aqi': 2}, 'components': {'co': 72.33, 'no': 0.07, 'no2': 1.4, 'o3': 36.09, 'so2': 1, 'pm2_5': 7.56, 'pm10': 24.39, 'nh3': 0.27}, 'dt': 1783998000}, {'main': {'aqi': 2}, 'components': {'co': 73.02, 'no': 0.11, 'no2': 1.43, 'o3': 37.29, 'so2': 1.04, 'pm2_5': 6.81, 'pm10': 20.52, 'nh3': 0.25}, 'dt': 1784001600}, {'main': {'aqi': 1}, 'components': {'co': 72.54, 'no': 0.12, 'no2': 1.32, 'o3': 39.2, 'so2': 1.04, 'pm2_5': 6.29, 'pm10': 17.66, 'nh3': 0.24}, 'dt': 1784005200}, {'main': {'aqi': 1}, 'components': {'co': 71.65, 'no': 0.12, 'no2': 1.16, 'o3': 41.32, 'so2': 1.01, 'pm2_5': 5.93, 'pm10': 15.75, 'nh3': 0.23}, 'dt': 1784008800}, {'main': {'aqi': 1}, 'components': {'co': 71.46, 'no': 0.13, 'no2': 0.91, 'o3': 44.26, 'so2': 0.95, 'pm2_5': 5.59, 'pm10': 14.23, 'nh3': 0.22}, 'dt': 1784012400}, {'main': {'aqi': 1}, 'components': {'co': 71.01, 'no': 0.13, 'no2': 0.75, 'o3': 46.28, 'so2': 0.88, 'pm2_5': 5.35, 'pm10': 13.6, 'nh3': 0.2}, 'dt': 1784016000}, {'main': {'aqi': 1}, 'components': {'co': 70.98, 'no': 0.14, 'no2': 0.68, 'o3': 47.2, 'so2': 0.84, 'pm2_5': 5.15, 'pm10': 13.11, 'nh3': 0.2}, 'dt': 1784019600}, {'main': {'aqi': 1}, 'components': {'co': 71.46, 'no': 0.14, 'no2': 0.66, 'o3': 47.38, 'so2': 0.8, 'pm2_5': 4.95, 'pm10': 12.41, 'nh3': 0.2}, 'dt': 1784023200}, {'main': {'aqi': 1}, 'components': {'co': 72.14, 'no': 0.15, 'no2': 0.72, 'o3': 46.97, 'so2': 0.8, 'pm2_5': 4.83, 'pm10': 11.83, 'nh3': 0.21}, 'dt': 1784026800}, {'main': {'aqi': 1}, 'components': {'co': 72.97, 'no': 0.16, 'no2': 0.87, 'o3': 46.27, 'so2': 0.82, 'pm2_5': 4.93, 'pm10': 12.07, 'nh3': 0.22}, 'dt': 1784030400}, {'main': {'aqi': 1}, 'components': {'co': 73.2, 'no': 0.13, 'no2': 1.11, 'o3': 44.67, 'so2': 0.87, 'pm2_5': 5.32, 'pm10': 13.88, 'nh3': 0.24}, 'dt': 1784034000}, {'main': {'aqi': 1}, 'components': {'co': 73.07, 'no': 0.03, 'no2': 1.42, 'o3': 42.37, 'so2': 0.99, 'pm2_5': 6.06, 'pm10': 17.14, 'nh3': 0.28}, 'dt': 1784037600}, {'main': {'aqi': 2}, 'components': {'co': 72.58, 'no': 0, 'no2': 1.48, 'o3': 40.55, 'so2': 1.05, 'pm2_5': 6.7, 'pm10': 20.06, 'nh3': 0.31}, 'dt': 1784041200}, {'main': {'aqi': 2}, 'components': {'co': 71.5, 'no': 0, 'no2': 1.43, 'o3': 39.35, 'so2': 1.07, 'pm2_5': 6.92, 'pm10': 21.06, 'nh3': 0.32}, 'dt': 1784044800}, {'main': {'aqi': 2}, 'components': {'co': 71.62, 'no': 0, 'no2': 1.48, 'o3': 38.9, 'so2': 1.11, 'pm2_5': 6.95, 'pm10': 20.69, 'nh3': 0.34}, 'dt': 1784048400}, {'main': {'aqi': 1}, 'components': {'co': 72.03, 'no': 0, 'no2': 1.5, 'o3': 38.69, 'so2': 1.1, 'pm2_5': 6.76, 'pm10': 19.5, 'nh3': 0.34}, 'dt': 1784052000}, {'main': {'aqi': 1}, 'components': {'co': 71.4, 'no': 0, 'no2': 1.46, 'o3': 38.39, 'so2': 1.06, 'pm2_5': 6.4, 'pm10': 18.05, 'nh3': 0.35}, 'dt': 1784055600}, {'main': {'aqi': 1}, 'components': {'co': 71.22, 'no': 0, 'no2': 1.4, 'o3': 38.08, 'so2': 1, 'pm2_5': 6.13, 'pm10': 17.23, 'nh3': 0.38}, 'dt': 1784059200}, {'main': {'aqi': 1}, 'components': {'co': 70.89, 'no': 0, 'no2': 1.31, 'o3': 37.83, 'so2': 0.94, 'pm2_5': 5.85, 'pm10': 16.54, 'nh3': 0.41}, 'dt': 1784062800}, {'main': {'aqi': 1}, 'components': {'co': 70.55, 'no': 0, 'no2': 1.22, 'o3': 37.67, 'so2': 0.88, 'pm2_5': 5.56, 'pm10': 15.94, 'nh3': 0.42}, 'dt': 1784066400}, {'main': {'aqi': 1}, 'components': {'co': 70.51, 'no': 0, 'no2': 1.13, 'o3': 37.63, 'so2': 0.84, 'pm2_5': 5.36, 'pm10': 15.81, 'nh3': 0.42}, 'dt': 1784070000}, {'main': {'aqi': 1}, 'components': {'co': 70.84, 'no': 0, 'no2': 1.1, 'o3': 37.51, 'so2': 0.83, 'pm2_5': 5.32, 'pm10': 16.18, 'nh3': 0.41}, 'dt': 1784073600}, {'main': {'aqi': 1}, 'components': {'co': 71.63, 'no': 0, 'no2': 1.19, 'o3': 37.36, 'so2': 0.87, 'pm2_5': 5.37, 'pm10': 16.66, 'nh3': 0.41}, 'dt': 1784077200}, {'main': {'aqi': 1}, 'components': {'co': 73.43, 'no': 0.01, 'no2': 1.48, 'o3': 37.21, 'so2': 0.97, 'pm2_5': 5.38, 'pm10': 16.45, 'nh3': 0.41}, 'dt': 1784080800}, {'main': {'aqi': 1}, 'components': {'co': 75.67, 'no': 0.04, 'no2': 1.81, 'o3': 37.3, 'so2': 1.11, 'pm2_5': 5.23, 'pm10': 15.19, 'nh3': 0.38}, 'dt': 1784084400}, {'main': {'aqi': 1}, 'components': {'co': 75.94, 'no': 0.06, 'no2': 1.67, 'o3': 38.92, 'so2': 1.03, 'pm2_5': 4.21, 'pm10': 10.63, 'nh3': 0.3}, 'dt': 1784088000}, {'main': {'aqi': 1}, 'components': {'co': 75.74, 'no': 0.07, 'no2': 1.42, 'o3': 41.01, 'so2': 0.89, 'pm2_5': 3.36, 'pm10': 7.65, 'nh3': 0.27}, 'dt': 1784091600}, {'main': {'aqi': 1}, 'components': {'co': 75.22, 'no': 0.07, 'no2': 1.25, 'o3': 42.42, 'so2': 0.83, 'pm2_5': 3.06, 'pm10': 6.67, 'nh3': 0.26}, 'dt': 1784095200}, {'main': {'aqi': 1}, 'components': {'co': 75.46, 'no': 0.08, 'no2': 1.1, 'o3': 44.34, 'so2': 0.79, 'pm2_5': 2.93, 'pm10': 6.19, 'nh3': 0.25}, 'dt': 1784098800}, {'main': {'aqi': 1}, 'components': {'co': 75.43, 'no': 0.09, 'no2': 1.01, 'o3': 45.91, 'so2': 0.79, 'pm2_5': 3.01, 'pm10': 6.25, 'nh3': 0.24}, 'dt': 1784102400}, {'main': {'aqi': 1}, 'components': {'co': 75.37, 'no': 0.11, 'no2': 0.95, 'o3': 47, 'so2': 0.79, 'pm2_5': 3.11, 'pm10': 6.45, 'nh3': 0.23}, 'dt': 1784106000}, {'main': {'aqi': 1}, 'components': {'co': 75.85, 'no': 0.12, 'no2': 0.96, 'o3': 47.61, 'so2': 0.84, 'pm2_5': 3.28, 'pm10': 6.89, 'nh3': 0.25}, 'dt': 1784109600}, {'main': {'aqi': 1}, 'components': {'co': 76.26, 'no': 0.14, 'no2': 1.09, 'o3': 46.74, 'so2': 0.89, 'pm2_5': 3.62, 'pm10': 7.99, 'nh3': 0.29}, 'dt': 1784113200}, {'main': {'aqi': 1}, 'components': {'co': 77.24, 'no': 0.17, 'no2': 1.28, 'o3': 45.9, 'so2': 0.92, 'pm2_5': 3.94, 'pm10': 9.18, 'nh3': 0.32}, 'dt': 1784116800}, {'main': {'aqi': 1}, 'components': {'co': 78.14, 'no': 0.15, 'no2': 1.54, 'o3': 44.56, 'so2': 0.92, 'pm2_5': 4.33, 'pm10': 10.98, 'nh3': 0.38}, 'dt': 1784120400}, {'main': {'aqi': 1}, 'components': {'co': 78.57, 'no': 0.04, 'no2': 1.84, 'o3': 42.43, 'so2': 0.99, 'pm2_5': 4.87, 'pm10': 13.18, 'nh3': 0.45}, 'dt': 1784124000}, {'main': {'aqi': 1}, 'components': {'co': 78.25, 'no': 0, 'no2': 1.91, 'o3': 40.6, 'so2': 1.05, 'pm2_5': 5.41, 'pm10': 14.83, 'nh3': 0.5}, 'dt': 1784127600}, {'main': {'aqi': 1}, 'components': {'co': 76.94, 'no': 0, 'no2': 1.83, 'o3': 39.39, 'so2': 1.09, 'pm2_5': 5.65, 'pm10': 15.45, 'nh3': 0.51}, 'dt': 1784131200}, {'main': {'aqi': 1}, 'components': {'co': 76.26, 'no': 0, 'no2': 1.79, 'o3': 38.94, 'so2': 1.14, 'pm2_5': 5.75, 'pm10': 15.53, 'nh3': 0.49}, 'dt': 1784134800}, {'main': {'aqi': 1}, 'components': {'co': 75.53, 'no': 0, 'no2': 1.75, 'o3': 38.6, 'so2': 1.15, 'pm2_5': 5.72, 'pm10': 15.22, 'nh3': 0.45}, 'dt': 1784138400}, {'main': {'aqi': 1}, 'components': {'co': 73.94, 'no': 0, 'no2': 1.62, 'o3': 38.13, 'so2': 1.11, 'pm2_5': 5.55, 'pm10': 14.56, 'nh3': 0.41}, 'dt': 1784142000}]}

In [20]:
forecast_data = response.json()["list"]

forecast_records = []

for item in forecast_data:
    forecast_records.append({
        "datetime": item["dt"],
        "AQI": item["main"]["aqi"],
        "CO": item["components"]["co"],
        "NO": item["components"]["no"],
        "NO2": item["components"]["no2"],
        "O3": item["components"]["o3"],
        "SO2": item["components"]["so2"],
        "PM2_5": item["components"]["pm2_5"],
        "PM10": item["components"]["pm10"],
        "NH3": item["components"]["nh3"]
    })

forecast_df = pd.DataFrame(forecast_records)

forecast_df.head()

     datetime  AQI     CO    NO   NO2     O3   SO2  PM2_5   PM10   NH3
0  1783731600    3  67.63  0.00  0.68  38.67  0.74  14.64  61.21  0.24
1  1783735200    3  68.75  0.01  0.88  38.99  0.81  14.09  58.51  0.25
2  1783738800    3  70.31  0.06  1.07  40.05  0.90  13.57  55.94  0.23
3  1783742400    3  71.19  0.12  1.03  43.18  0.95  13.26  55.49  0.20
4  1783746000    3  71.06  0.14  0.80  47.91  0.95  12.99  53.78  0.18

In [21]:
forecast_df.to_csv("../data/raw/aqi_forecast_data.csv", index=False)
print("Forecast dataset saved successfully.")

Forecast dataset saved successfully.

In [22]:
saved_df = pd.read_csv("../data/raw/aqi_forecast_data.csv")
saved_df.head()

     datetime  AQI     CO    NO   NO2     O3   SO2  PM2_5   PM10   NH3
0  1783731600    3  67.63  0.00  0.68  38.67  0.74  14.64  61.21  0.24
1  1783735200    3  68.75  0.01  0.88  38.99  0.81  14.09  58.51  0.25
2  1783738800    3  70.31  0.06  1.07  40.05  0.90  13.57  55.94  0.23
3  1783742400    3  71.19  0.12  1.03  43.18  0.95  13.26  55.49  0.20
4  1783746000    3  71.06  0.14  0.80  47.91  0.95  12.99  53.78  0.18